language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install

script:
  - vendor/jakub-onderka/php-parallel-lint/parallel-lint --exclude vendor .

before_deploy: "zip -r 'Allow-EEcode' allow_eecode"

deploy:
  provider: releases
  api_key:
    secure: cCoMek9WIVzWnYe2Ts4gr/x0Wxkcug3pWGzYMqbk9OcipAJP3u5HqxWp56N9wghNQVijRqNiMOnJoBahg3dgfMqRNkkgRip5r+7YWVNxDsOkZfkA5OrtX8W3U5+PiYIzWrOkpoC37IJJuAJCePBdqVbO8l7xrpKA8fTdMzHezPZ7UG0jIIg/8MTEZsuXZ2ghaS9OCSymgZ4bfuOWdAP5spRWn39nNvfU8qiDQFy6sW8xe0r3Kp/ixtabKWLanrmfNKPw1MFdigHEfpXnbWZRHXUNR0wqDv+wD9QVsOYcpZq0S63pv8liN0Q5hPCNpmM8aQ4a+E8tkDMSaPEt02SRLPbBIUszmaXGoITeBAQXfCGu+fAGYrcJ0tiI3V8/E4gyBOJb+yNfv0MyfZbDUN2ZkIfxkz+yiGr08g42IaphMq2oGVVSPj/OlOh6URhLh7LAZiUz/UEounukLSVV4sDvYKtySXxFcIj6swcumKBhuqSnUekBco7oToXw/qA42vVn8itkrFtUxSI4R7Rm3Px7QRfNb9vfc6Y6rT2zviTVfF7lq/PHVpA0PizjGW8k3jmxQDB2h23wRwvmExe4y42YqRVCCMWxhOA4rOehB+qzJEpwXiE+6wli/E5jQO2d+1Ltmb0EJtIF4GyMbxJc0N8cP79+APbu1k19IMf2/xgoRYQ=
  file: "Allow-EEcode.zip"
  skip_cleanup: true
  on:
    php: 7.0
    tags: true
    condition: $TRAVIS_PULL_REQUEST = false
