language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install

script:
  - vendor/jakub-onderka/php-parallel-lint/parallel-lint --exclude vendor .

before_deploy: "zip -r 'Allow-EEcode' allow_eecode"

deploy:
  provider: releases
  api_key:
    secure: nq6vIfiE4DfVTM7xFXNcrBNnnGh1crUaAe4Y9InbpaIRrEU3Slvu9uXFCYfltxkANtg842IYVNRlHbpknwo4dEag+TcjsPoO59l4BazCa/HoNS0u8NJamWFdNXqwzw86X6ANbGUOLSsksyQYO/bGFRg5BF+VZAqDysKAYMz618A=
  file: "Allow-EEcode.zip"
  skip_cleanup: true
  on:
    php: 7.0
    tags: true
    condition: $TRAVIS_PULL_REQUEST = false
